### ISSUE TITLE
[REQUEST] System tray options

### ISSUE THREAD

**Issue by ImportTaste** [UWPCommunity/Quarrel#101]
_Well after paying the ad removal fee, I'm feeling all entitled now - time to submit feature requests._

When something is going to be running basically all the time, I like to have the option to minimize it to the system tray. For completion's sake, there should probably be a Close to tray option too.

Naturally, the system tray icon should show an indicator for unread messages (or better yet, a number for how many unread messages there are).

**Comment by matthew4850** [comment]
Uwp does not support the system tray so this is not something that can be done.

**Comment by ImportTaste** [comment]
@matthew4850 Doesn't EarTrumpet use the system tray?

**Comment by ImportTaste** [comment]
@matthew4850 https://github.com/File-New-Project/EarTrumpet/search?q=tray&unscoped_q=tray

MIT License

**Comment by matthew4850** [comment]
@ImportTaste I am not familiar with that software but as far as I am aware the only way for system tray support would be to declare runFullTrust which is difficult to get store certification for and is not something we are looking to do right now.

**Comment by matthew4850** [comment]
@ImportTaste After looking through the source you liked it looks like they do declare the runFullTrust capability, I would not count on Quarrel adding this feature any time soon.

**Comment by ImportTaste** [comment]
@matthew4850 It is actually not hard at all, a friend of mine got runFullTrust capability for his UWP app recently. All you have to do is submit a dashboard issue at https://developer.microsoft.com/en-us/windows/support and say that you want to add a system tray to your app, and they'll approve it within a few business days.

**Comment by matthew4850** [comment]
@ImportTaste I am not ruling it out completely but we are much more focused on rewriting quarrel than adding new features at the moment.

**Comment by MarcAnt01** [comment]
That's a duplicate of kinda of https://github.com/UWPCommunity/Quarrel/issues/52
