### ISSUE TITLE
[SUGGESTION] User join / User leave Notifications should be off by default

### ISSUE THREAD

**Issue by ImportTaste** [UWPCommunity/Quarrel#104]
I think people who use Discord a lot are going to be the most interested in this app, because Discord uses Electron, which feels sluggish once you start dealing with lots of servers and friends. Seeking out an alternative is what led me to Quarrel.

So, as someone with a lot of people on my friends list, I was being driven crazy trying to figure out where all those pinging sounds were coming from. 'User join' & 'User leave' notifications were the culprit.

**Comment by matthew4850** [comment]
Are you referring to voice channels?

**Comment by ImportTaste** [comment]
![image](https://user-images.githubusercontent.com/53661808/69080080-eb2b9080-0a00-11ea-90fb-b5778177bc22.png)

**Comment by Avid29** [comment]
Not relevant to new Quarrel
