### ISSUE TITLE
Share a content to Quarrel

### ISSUE THREAD

**Issue by MarcAnt01** [UWPCommunity/Quarrel#109]
At the moment it's not possible share a content from an app to Quarrel

**Comment by Avid29** [comment]
Duplicate of #108

**Comment by MarcAnt01** [comment]
> Duplicate of #108

No, that issue is sharing FROM this one is sharing TO

**Comment by Avid29** [comment]
Got it

**Comment by Avid29** [comment]
Or you changed the other one. I prefer it like that. Reclosing...

**Comment by MarcAnt01** [comment]
> Or you changed the other one. I prefer it like that. Reclosing...

@matthew4850 has done that.

Anyway, I'll edit the other issue to be meant like you prefer
