### ISSUE TITLE
Exception on start on mobile

### ISSUE THREAD

**Issue by WallyCZ** [UWPCommunity/Quarrel#110]
(Windows.UI.Xaml.Markup.XamlParseException) 
Cannot find a Resource with the Name/Key DefaultMenuFlyoutPresenterStyle [Line: 49 Position: 21]

Phone Version         : 10.0.15254
Windows Version     : 10.0.15254.600
OS Build                  : 15254.feature2_rs3svc(winpbld).20191127-1832
Quarrel                   : 19.12.27

**Comment by matthew4850** [comment]
What triggered this exception, is this when you opened Quarrel?

**Comment by WallyCZ** [comment]
Yep, it crashes after app start whilst that big Quarrel splash logo is rotating (even before some first page could appear)
