### ISSUE TITLE
Make up arrow edit last message in current tab.

### ISSUE THREAD

**Issue by ImportTaste** [UWPCommunity/Quarrel#118]
This is a keyboard shortcut I use all the time in Discord and I keep doing it in Quarrel out of habit, only to have nothing happen.

**Comment by SamCraftRecon** [comment]
Last I heard from the developers of Quarrel, they said that it wasn't an easy thing to add. May be different now but I can't say for sure.

**Comment by Avid29** [comment]
I'll look into it, the rewrite is a whole new beast and everything works better. I think I can do it pretty easily actually

**Comment by Avid29** [comment]
Done for rewrite
