### ISSUE TITLE
Store Update?

### ISSUE THREAD

**Issue by ImportTaste** [UWPCommunity/Quarrel#125]
Is there any reason why this app isn't receiving updates on the Microsoft Store? It's still on an old pre-rewrite build.

**Comment by matthew4850** [comment]
The rewrite is still in progress, we are not updating the non-insider build until the rewrite is complete

**Comment by ImportTaste** [comment]
By non-insider build, do you mean compiling it on our own? Because I'm in the Windows Insider program.

**Comment by Avid29** [comment]
There's a separate app in the windows store. "Quarrel Insider"

**Comment by ImportTaste** [comment]
@Avid29 Found it, thanks.

**Comment by ImportTaste** [comment]
@matthew4850 I was enjoying testing all the new features but there hasn't been a new insider build since the 2nd, will this be changing any time soon?
