### ISSUE TITLE
Emoji do not render properly

### ISSUE THREAD

**Issue by matthew4850** [UWPCommunity/Quarrel#126]
Discord
![image](https://user-images.githubusercontent.com/40522069/73576277-fe7fc100-4471-11ea-8513-079b54c3ea0a.png)
Quarrel
![image](https://user-images.githubusercontent.com/40522069/73576302-0b041980-4472-11ea-8950-b0fbcee9a43f.png)

**Comment by MarcAnt01** [comment]
> Discord
> ![image](https://user-images.githubusercontent.com/40522069/73576277-fe7fc100-4471-11ea-8513-079b54c3ea0a.png)
> Quarrel
> ![image](https://user-images.githubusercontent.com/40522069/73576302-0b041980-4472-11ea-8950-b0fbcee9a43f.png)

What's the problem?

**Comment by matthew4850** [comment]
@MarcAnt01 ideally I would like the emoji to have the same style as discord's emoji and some of the emoji do not render at all :a: is an example of that.

**Comment by Avid29** [comment]
![image](https://user-images.githubusercontent.com/9384045/73906225-2e630600-4870-11ea-98b7-5078167590d3.png)
Fixed

**Comment by matthew4850** [comment]
not all emoji render properly still
Discord
![image](https://user-images.githubusercontent.com/40522069/74033072-4db37d80-49ad-11ea-849c-9057f9179a7f.png)
Quarrel
![image](https://user-images.githubusercontent.com/40522069/74033095-56a44f00-49ad-11ea-92c9-ed72a71b918c.png)

**Comment by MarcAnt01** [comment]
> not all emoji render properly still
> Discord
> ![image](https://user-images.githubusercontent.com/40522069/74033072-4db37d80-49ad-11ea-849c-9057f9179a7f.png)
> Quarrel
> ![image](https://user-images.githubusercontent.com/40522069/74033095-56a44f00-49ad-11ea-92c9-ed72a71b918c.png)

Maybe Discord emojis are a bit complex, but shouldn't making an own emoji font solve this kind of issue?

**Comment by matthew4850** [comment]
no, the problem is the parsing
