### ISSUE TITLE
Frequent crashing during basic operation

### ISSUE THREAD

**Issue by ctaetcsh** [UWPCommunity/Quarrel#127]
I am running Windows 10 Pro 1909 Build 18363.592. 
I have a Ryzen 3 1200 & an RX 480.

During regular operation, such as chatting in a server, the application will spontaneously crash with no error message or indication of the problem. From what I understand this has been going on for a while, but I wanted to know if there was a fix in the works, or a way I could send debugging information to help with fixing it. 
Quarrel is a really good port for UWP and I am glad to see where it will go.

**Comment by Avid29** [comment]
Is this on the rewrite (insider) or the original?

**Comment by ctaetcsh** [comment]
I am running the version in the Microsoft Store labeled Quarrel. I looked at other issues that mentioned a Quarrel Insider but I was unable to find that.

**Comment by Avid29** [comment]
https://www.microsoft.com/store/apps/9NN1ZFD5G6DL
That's a link to the Quarrel Insider app
In 4 months all the work going on there will be released for the standard app

**Comment by ctaetcsh** [comment]
Okay, thank you!
