### ISSUE TITLE
Fix System.Collections.Generic.KeyNotFoundException in BindableChannel.<get_ChannelMembers>b__53_0 (User x)

### ISSUE THREAD

**Issue by matthew4850** [UWPCommunity/Quarrel#157]
### Stacktrace ###

GalaSoft.MvvmLight.Helpers.WeakAction.Execute();GalaSoft.MvvmLight.Helpers

### Reason ###

System.Collections.Generic.KeyNotFoundException

### Link to App Center ###

* [https://appcenter.ms/users/matthew4850/apps/Quarrel/crashes/errors/2520569813u](https://appcenter.ms/users/matthew4850/apps/Quarrel/crashes/errors/2520569813u)

**Comment by Avid29** [comment]
Not reproducible on modern builds
