### ISSUE TITLE
Messaging via contacts

### ISSUE THREAD

**Issue by wiesmin138** [UWPCommunity/Quarrel#158]
I've just discovered that Quarrel has integration with Windows Contacts app.
Would be really nice to be able to chat using Contacts, especially using this little box that appear if you pin contact to taskbar.

![image](https://user-images.githubusercontent.com/54535486/77855683-4ca30d80-71f2-11ea-8aab-1a1aa5c20cf7.png)

**Comment by matthew4850** [comment]
This should be working already.

**Comment by wiesmin138** [comment]
well, nope
You can write, but it doesn't send anything.

**Comment by wiesmin138** [comment]
> This should be working already.

@matthew4850 it **should**, but is **not** working.
