### ISSUE TITLE
crashing on launch - Windows

### ISSUE THREAD

**Issue by salmanmkc** [UWPCommunity/Quarrel#159]
Windows 10 Build 18363, the latest store version

**Comment by matthew4850** [comment]
Is this the insider version of quarrel?

**Comment by salmanmkc** [comment]
non-insider build, just from the store

**Comment by matthew4850** [comment]
We are focusing all our efforts on the insider build right now as it is a total rewrite, as such we will not be fixing any bugs in the old version.
