### ISSUE TITLE
Add a widget to the Windows Game Bar using the new SDK

### ISSUE THREAD

**Issue by Airyzz** [UWPCommunity/Quarrel#163]
**Is your feature request related to a problem? Please describe.**
The official discord overlay is implemented using what seems to be a janky DX Hook. Due to the fact that this app is created for UWP and the Windows Game Bar is also using UWP, it seems to present a unique opportunity for this app to implement a great discord overlay, better than what is currently provided by discord.

**Describe the solution you'd like**
A Quarrel / Discord Widget implemented into the Windows Game Bar using the new [SDK](https://docs.microsoft.com/en-gb/gaming/game-bar/)

**Describe alternatives you've considered**
Asking Discord on twitter if they are planning to implement such a feature, but as the SDK is still very new, there is not much else in terms of alternatives

**Comment by matthew4850** [comment]
This is something we plan to do, I am not sure when yet.
