### ISSUE TITLE
Xbox-Version is (very) unstable ...

### ISSUE THREAD

**Issue by Alpengreis** [UWPCommunity/Quarrel#164]
Sometimes I couldn't login on Discord, it seems I had then to close the app and restart to be successful OR even worse, I had to reset the app completely ...

If I open certain channels or at least after trying to scroll a bit, the app crashes.

EACH time after trying to make a quote reply, the app crashes.

Sometimes it seems the app just crashes ...

PS: I tried of course also the "trick" with reset Quarrel ...

**Comment by matthew4850** [comment]
Is this the insider version of quarrel?

**Comment by Alpengreis** [comment]
Hmm downloaded over the normal MS store ... I will check it out more exactly and post then here again ...

**Comment by matthew4850** [comment]
If you just downloaded it the normal way (not through the special link from the discord server) then it will be the old version of Quarrel. We are currently rewriting Quarrel to make everything better and as such we are not fixing the old version anymore, we expect to release the rewrite in June.

**Comment by Alpengreis** [comment]
Ahh, ok, ty! I will try in this case the insider!

**Comment by Alpengreis** [comment]
PS: I have insider version now: after trying to edit an own msg, crash!

**Comment by matthew4850** [comment]
Does this happen every time?

**Comment by Alpengreis** [comment]
Not always direct after I click to edit - sometimes it opens the text to edit yet - but there, after I press button B till to cancel (few times), the app crashes.

If it crashes direct after I click to edit, the app restarts automatically. If it open the text yet, it crashes without automatic restart.
