### ISSUE TITLE
Notification Settings Ignored

### ISSUE THREAD

**Issue by scratchfive** [UWPCommunity/Quarrel#25]
Notification settings toggles for "User Join" and "User Leave" under the Windows subheading are seemingly ignored by the app. These should disable notification sounds for their respective settings, but no change is made regardless of the toggle.

**Comment by Tourniquet88** [comment]
Yeah I can confirm that, sadly. :P

**Comment by ray1997** [comment]
It look like GatewayManager is straight up playing the sound when user is disconnect and connect into voice chat without looking into the settings as seen on "https://github.com/UWPCommunity/Quarrel/blob/dev/Discord%20UWP/Managers/GatewayManager.cs" line 879 and 882
Seems easy to fix, just add `if (Storage.Settings.UserJoinSound)' above
But recent news, the dev is rewriting the whole thing. So it might be pointless to fix it now. Just bear with it for now

**Comment by matthew4850** [comment]
Rewriting the whole thing is going to take a long time, can you make a pu request with those changes?

**Comment by ImportTaste** [comment]
@scratchfive @matthew4850 This issue should be closed.

@matthew4850 Might I recommend [probot-stale](https://github.com/probot/stale) to help prevent the issue list getting out of hand? I see that happen with so many projects these days.

**Comment by matthew4850** [comment]
@ImportTaste Thanks, it has now been closed.
