### ISSUE TITLE
Background voice is not working, and Voip causing occasional crash

### ISSUE THREAD

**Issue by Avid29** [UWPCommunity/Quarrel#341]

**Comment by Waddle-Doo** [comment]
Addendum here, backround voice is currently functional but because execution is suspended Discord's server times out the connection. 
There's also weird issues with establishing a connection. #395 can probably be merged with this issue.

**Comment by matthew4850** [comment]
> Addendum here, backround voice is currently functional but because execution is suspended Discord's server times out the connection.
> There's also weird issues with establishing a connection. #395 can probably be merged with this issue.

While this is todo with voice it is unrelated, please create a new issue.
Also, this was fixed a while ago and should be closed.
