### ISSUE TITLE
Server list gets duplicated randomly

### ISSUE THREAD

**Issue by ArttuLai** [UWPCommunity/Quarrel#343]
Noticed this issue after installing v20.6.13 from the Store. Occasionally my server list duplicates itself, feels random to me. Only way I've found to fix it is to restart the app.
<img width="898" alt="explorer_K2WXoLkj" src="https://user-images.githubusercontent.com/42007282/84557717-0f9ce080-ad36-11ea-914d-685697aeeb6e.png">

**Comment by Negociation** [comment]
The same happens to me (Mobile and PC). It happens after the app reload on background, apparently after the app reload its concating the server list with itself again, instead of replace it...
