### ISSUE TITLE
Loss of voice and audio

### ISSUE THREAD

**Issue by TrickyDee42** [UWPCommunity/Quarrel#346]
Love what you guys are doing, seems super light weight.

But I have noticed that although it works fine in game for a while, after half an hour or so, I notice that it has gone quiet, and no one can hear me.

Have to revert back official, as can not lose comms half way through a endurance sim race.

Keep up the good work.

**Comment by Avid29** [comment]
On Xbox?
We neglected to test background voice (on any device) without a debugger attached and it does not work. We're working full throttle to fix this asap, but we're not certain why it's not working at this point. This is a duplicate issue of #341 and #331 so I'm going to mark it as a duplicate and close it

**Comment by Avid29** [comment]
P.S. If this is on PC you can fix it for now by not minimizing the window, as inconvenient as this is.

**Comment by TrickyDee42** [comment]
It is on PC, and thanks for the tip
