### ISSUE TITLE
Leaving servers 

### ISSUE THREAD

**Issue by TigerNotice** [UWPCommunity/Quarrel#355]
Hello. Ive got another issue.
So I'm trying to leave servers and I click "Leave server" and nothing is happening. This can get frustrating because they're always giving me notifications every so often.

Hope you can fix the issue,
Cal.

**Comment by Waddle-Doo** [comment]
I'm just a tester and have no authority on this, but a full week has passed since this was reported and neither me or any of the repo owners have had any success reproducing this. I personally believe this issue can be closed.

**Comment by Waddle-Doo** [comment]
This should be closed as the issue is outdated, vague, unsubstantiated, and unreproduceable.
