### ISSUE TITLE
Errors in compiling

### ISSUE THREAD

**Issue by MarcAnt01** [UWPCommunity/Quarrel#37]
I get these erros while attempting to build the solution
![image](https://user-images.githubusercontent.com/43090263/59161854-f7bdcb80-8ae7-11e9-83b4-73412749385d.png)

**Comment by matthew4850** [comment]
You need to install windows sdk version 10.0.17134.0.
![screen](https://user-images.githubusercontent.com/40522069/59161905-6d259e00-8ae0-11e9-9a92-d3dbe4425e2a.jpg)

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/59162381-2c358580-8af0-11e9-969b-a07ff54f9334.png)

**Comment by matthew4850** [comment]
Please install .net framework version 4.6.1

**Comment by MarcAnt01** [comment]
@matthew4850 I need 4.7.2 for other projects, can I install 4.6.1 along with 4.7.2?

**Comment by matthew4850** [comment]
yeah, just go back into the visual studio installer and check ".NET Framework 4.6.1 SDK"

**Comment by MarcAnt01** [comment]
Seems it is already enabled
![Uploading image.png…]()

**Comment by matthew4850** [comment]
Could you repost the image?

**Comment by MarcAnt01** [comment]
> Could you repost the image?

Sure, looks as GitHub fucked the picture

![image](https://user-images.githubusercontent.com/43090263/59162733-8afdfd80-8af6-11e9-86ff-9af54ba6a316.png)

**Comment by MarcAnt01** [comment]
I have also chosen to target 4.6.1 for the project

**Comment by matthew4850** [comment]
When you open up the solution in visual studio, do you see this
![Annotation 2019-04-26 204238](https://user-images.githubusercontent.com/40522069/59162861-2a6bc200-8af0-11e9-9c72-3c379f9b1957.jpg)
If so press ok then build sodiumC and then try to build quarrel.

**Comment by matthew4850** [comment]
When you open up the solution in visual studio, do you see this
![Annotation 2019-06-09 195243](https://user-images.githubusercontent.com/40522069/59162868-4707fa00-8af0-11e9-8210-f63a995e7206.jpg)
If so press ok then build sodiumC and then try to build quarrel.

**Comment by MarcAnt01** [comment]
Yes, I see that, but I still get the error when building the solution, should I directly build the app?

**Comment by matthew4850** [comment]
Try building sodiumC then building quarrel.

**Comment by MarcAnt01** [comment]
Building sodiumC had no problems, but building Quarrel wasn't succesful
![image](https://user-images.githubusercontent.com/43090263/59162984-9bb07280-8afa-11e9-858d-5c53a4a51e9d.png)

**Comment by MarcAnt01** [comment]
For who's struggling building the old quarrel, those steps worked for me:
- download the required .NET framework version;
- build the solution;
- build SodiumC;
- deploy Quarrel
