### ISSUE TITLE
Bot user's 'fake' usernames are compressed into one message

### ISSUE THREAD

**Issue by wryun** [UWPCommunity/Quarrel#374]
I use https://github.com/42wim/matterbridge/

Basically, this means that users from other platforms all come through via the same bot, but override the username (via Execute Webhook):

https://discord.com/developers/docs/resources/webhook#execute-webhook

Unfortunately, Quarrel ignores the differing username of subsequent bot messages, presumably thinking it's the same user, so rather than getting:

> PersonA Hi!
> PersonB How's it going?
> PersonA Ok, I guess...

I get:
> PersonA Hi!
>     How's it going?
>     I guess...

**Comment by Avid29** [comment]
Got it, we need to distinguish by both userId and Display name

I'll get this in the next patch, which might be a little while since I'm working on a pretty big refactor

**Comment by wryun** [comment]
Awesome, thanks! Err, please don't drop Windows 10 Mobile in the refactor :)
