### ISSUE TITLE
Profile Page interaction buttons [Send Friend Request, Block, Send Message, etc] do not update and do not send any request, act as non-functional.

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#376]
Tested and reproduced on Xbox One, Quarrel Insider 20.6.19. Of note is that this issue has been present since Version 20.6.7, but I cannot confirm if it mirrored the same behavior at that time.

**Comment by Waddle-Doo** [comment]
I'm wondering if I could get some kind of update on the status of looking into this issue. I understand higher priorities exist but I think the functionality of these elements is pretty important in terms of feature pairity.

**Comment by Avid29** [comment]
I'm working on it right now, I can't believe I forgot about this issue
