### ISSUE TITLE
the function for stacking and reverting to previous subpages extends to every subpage the user opens during runtime, even after closing. Causes unexpected behavior.

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#378]
Tested and reproduced on Xbox One, Quarrel Insider 20.6.19.

Reverting to previous subpages throwing a variety of errors, including these three most common:

InvocationException when loading profiles

NullReferenceException when loading server settings pages

The ability to load an "empty" profile page and cause a NullReferenceException when interacting with them.

This issue may be system specific as using the B button on an Xbox Controller to exit a subpage is what causes this.

**Comment by Avid29** [comment]
>This issue may be system specific as using the B button on an Xbox Controller to exit a subpage is what causes this.
That's ridiculously important. I'll check it out

**Comment by Waddle-Doo** [comment]
I want to note that this issue could potentially be fixed by any redesign of the subpages that would also close #500
