### ISSUE TITLE
Quarrel login temperamental 

### ISSUE THREAD

**Issue by VladimirAkopyan** [UWPCommunity/Quarrel#38]
Hello, when I log in with Quarrel, it goes to the connecting screen ,sand stays there forever. 
I am in UK, tried two different PCs, is that a known issue or am i doing something wrong? 
![image](https://user-images.githubusercontent.com/12278048/59196893-d6acb780-8b87-11e9-8ee9-c1af2c7b6236.png)

**Comment by Avid29** [comment]
@VladimirAkopyan I'm confused, that's not Quarrel. That's the Discord Inc. splash, but it's the UWP TitleBar.

**Comment by VladimirAkopyan** [comment]
I am too! 
Now I have: 
https://youtu.be/pR8V_1HxZWM
Then I restarted the app and I am logged in and all is well! 
![image](https://user-images.githubusercontent.com/12278048/59197374-11631f80-8b89-11e9-89ed-6c3d6668bc47.png)

**Comment by Avid29** [comment]
@VladimirAkopyan That happens sometimes, restart will almost always do it. I'll look into fixing it but I'm really confused by that previous screenshot. Quarrel doesn't load with that view

**Comment by VladimirAkopyan** [comment]
At first I had "discord thinks you are a bot" and then I get a webpage pop up with captua, etc. I think from then onwards it was discord in a browser window? I don't know

**Comment by Arlodotexe** [comment]
I got this issue when signing in the first time on Xbox as well

**Comment by lKobi** [comment]
Restarding did nothing, I never been able to login into Quarrel, I just use the Web version of Discord.

Also, https://github.com/UWPCommunity/Quarrel/issues/41

**Comment by Arlodotexe** [comment]
I should clarify. the first time I signed into Quarrel on Xbox, it took me to the webview
