### ISSUE TITLE
System Exception when double click a server icon

### ISSUE THREAD

**Issue by ricdizio** [UWPCommunity/Quarrel#381]
System Exception when double click a server icon. It seems to be changing some variable in the UI that is not in the same thread.

**Exception message:**
System.Exception: 'The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))'

![image](https://user-images.githubusercontent.com/22679695/85193508-0c49ad80-b27e-11ea-8e3c-b5f03cc18c47.png)

**File Name:** UWP\Quarrel\src\Quarrel\StateTriggers\BooleanStateTrigger.cs

**Comment by Avid29** [comment]
This appears to be fixed with the ``service_dilution`` branch. But I'll leave it open until that's merged because I'm not certain

**Comment by ricdizio** [comment]
Ok, I can check that. Thanks for reply.
