### ISSUE TITLE
Having animated images auto play may contribute to high cpu usage

### ISSUE THREAD

**Issue by ShinzenATT** [UWPCommunity/Quarrel#383]
By default Quarrel auto plays all animated pictures which can lead to high cpu usage when there are a lot of members that have animated profile pictures. So maybe change so they play on hover like in the official discord client in order to reduce cpu usage. Though I have no idea how much impact on performance this change may have.

**Comment by Waddle-Doo** [comment]
This issue may qualify to be reopened, as all animated images still autoplay on Xbox as of Insider 20.7.15, and embed GIFV files erroneously auto-play with audio.
