### ISSUE TITLE
Individual volume controls

### ISSUE THREAD

**Issue by MadafakinRio** [UWPCommunity/Quarrel#387]
Add the ability to control the volume of each individual user in a voice channel.

**Comment by plawsworth** [comment]
+1 one on this function. I would be happy enough with the ability to balance the Quarrel volume vs the overall volume. So that if I play a game I would like to change the volume of Quarrel separate from the game volume.

**Comment by TwitchyFrost** [comment]
Yes please. Even if there was just a way to lower the volume of quarrel. Even if its in the app.
