### ISSUE TITLE
Editing your own nickname

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#388]
Tested and reproduced on Xbox One, Quarrel Insider 20.6.21.

Because of this I am unable to declare my status as an anime catgirl. Disappointing, nya.

**Comment by Avid29** [comment]
This is because the feature isn't written at all yet, not because it thinks you can't

**Comment by Avid29** [comment]
It's easy to add changing your own nickname, so I'm adding that right now and I'll make another issue for editing the nickname of others
