### ISSUE TITLE
/fakepath/Quarrel/Discord UWP?

### ISSUE THREAD

**Issue by lazerl0rd** [UWPCommunity/Quarrel#39]
I'm pretty unaccustomed to seeing a folder such as `Discord UWP` in the top level of the source, I was wondering if there's a reason why it wasn't named `DiscordUWP`?

**Comment by MarcAnt01** [comment]
Agree with you, having it called Discord Uwp would be better, but I think there would be some problems with Discord Inc.

**Comment by Avid29** [comment]
Frankly ``src`` seems better. Might change that at somepoint
