### ISSUE TITLE
[Feature Pairity Request/Enhancement] reintroduce circular icons for user activity status to provide accessability for colorblindness

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#391]
I personally think Quarrel should still be supplementing the new glow effects with some kind of icons, specifically drawn ones that can be differentiated in monochrome. This is the same reason Discordapp switched to the new icons they're using instead of just the colored circles.

**Comment by BreeceW** [comment]
Accessibility should never be low priority.

**Comment by matthew4850** [comment]
> Accessibility should never be low priority.

To be clear I am not saying accessibility is low priority, just this specific UI change. If you would like to submit a PR making this change I would happily merge it.
