### ISSUE TITLE
Getting the discord server status page causes a crash.

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#396]
Tested and reproduced on Xbox One, Quarrel Insider 20.6.25.

The behavior of this is weirdly inconsistent. Sometimes throws an arg_nullreferenceexception, sometimes doesn't trip the crash handler at all.

I suspect Discord has changed the way their API makes this work.

**Comment by D181t1z3d** [comment]
I have that same error message on my Xbox too, I get it whenever I've clicked on the status.

**Comment by matthew4850** [comment]
This should be fixed in the most recent build.
