### ISSUE TITLE
Quarrel on android

### ISSUE THREAD

**Issue by bdashore3** [UWPCommunity/Quarrel#40]
Since windows mobile is dead, why not make quarrel for android?

**Comment by matthew4850** [comment]
No

**Comment by ray1997** [comment]
...open sourcing this is a mistake 😫

**Comment by Avid29** [comment]
@ray1997 what's the problem?

**Comment by ray1997** [comment]
I'm just getting annoyed by the people asking for an android version of UWPs apps. Even though it very obvious that it unlikely to happen. And the official app is already exist on android.
No hate, but disappointed. <3

**Comment by Avid29** [comment]
I got that **way** before this went opensource

**Comment by ray1997** [comment]
I know, because I've been in your server for a long time and see that happen (I'm ToonWk btw.)
