### ISSUE TITLE
Switching from a channel with a topic to one without doesn’t clear the topic in the header

### ISSUE THREAD

**Issue by BreeceW** [UWPCommunity/Quarrel#401]
Steps to reproduce:

- Open Quarrel
- Select a channel that you know doesn’t have a topic set
- The topic shows empty as expected
- Select another channel with a non-empty topic
- Go back to the channel without a topic

The topic is not cleared and shows the topic from the last channel instead.

**Comment by Waddle-Doo** [comment]
Wanted to note I reproduced this and I'm honestly baffled as to how I missed this. Xbox One and PC, Quarrel Insider 20.6.28. 

Some say that, to this day, the bike lane is still closed.

**Comment by Avid29** [comment]
We've fixed this before but I believe the null bindings issue reintroduced it
