### ISSUE TITLE
the handling for not allowing the user to send a message in a blocked direct message channel is unimplemented, causes a 403 to get thrown

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#409]
Tested and reproduced on Xbox One, Quarrel Insider 20.6.28

**Comment by Avid29** [comment]
The send message button and drafting text box should be greyed out. How are you sending messages in these channels?

**Comment by Waddle-Doo** [comment]
because they aren't actually greyed out?

**Comment by Waddle-Doo** [comment]
Edited to reflect an error in my clarification of this bug.

**Comment by Waddle-Doo** [comment]
This is fixed, it doesn't crash anymore. Yay.
