### ISSUE TITLE
[IMPORTANT] Stop using /api/login for authentication

### ISSUE THREAD

**Issue by 3reetop** [UWPCommunity/Quarrel#41]
Doing any user API things, such as using the `/user/login` or the MFA endpoints are bannable offenses by Discord.

Use token auth, ask users to copy over their token from the official client's localStorage.token value

Continuing to use `/user/login` will get this app banned from connecting to Discord altogether, they really do not like third party clients using those endpoints.

Just warning ya, whether or not you will actually do anything about this is up to you.

**Comment by xDrixxyz** [comment]
Oh and in case I misinterpreted something and you aren't using `/api/login` then I sincerely apologize. But from what I've seen it looks like you are asking the user for their email and password and using that to authenticate via `/api/login`
