### ISSUE TITLE
General audio distortion and/or delays with Forza Horizon 4 running.

### ISSUE THREAD

**Issue by cynojien** [UWPCommunity/Quarrel#440]
So far I've had a good experience with this app. It seems to work fine with every game I've run with it except for Forza Horizon 4. I suppose this could be another memory issue (I've sen quite a few of those) but I'm inclined to think it might be another issue. 

On two separate occasions I got two different issues with this app with Forza Horizon 4 running. The first time around the game audio and the chat audio were distorted. I was playing the chat/discord audio through the headset but both sources would randomly change pitch and just drop for a second before coming back in. On the games end this seemed to be more an issue with the music but sometimes there would be issues with the car audio as well. The game also noticeably skipped frames quite often. That said, Quarrel never crashed or dropped out of the call.

On the second attempt this morning it seemed to work much better. These were a few frame skips when first getting in to the game but it cleared up pretty quick. The call seemed to hold up fine quality wise but after about 5 minutes it would start to delay with transmitting. Things I would say wouldn't get to the others in the chat for roughly 2-4 seconds. After a few more minutes this got worse, taking about 8 seconds for my audio to get to others. Shortly afterwards it just stopped transmitting at all. Receiving audio from others seemed fine with no delay even after my chat audio just stopped transmitting. When switching to the app I found it was still running but the audio never caught up. I had to leave the call and rejoin. The same issues occurred in about the same amount of time after that.

I don't have much information aside from that but I figured I'd bring it up. If there is anyway for me to log or attempt to fix anything do let me know and I'll give it a try.

**Comment by Waddle-Doo** [comment]
This is an issue with Forza Horizon 4's audio programming related to memory intensive backround apps that has been present for quite some time, and is not directly related to Quarrel. This issue can probably be closed.



[Sourced: Reproduced by running Spotify and Soundcloud, and by broadcasting gameplay.]

**Comment by cynojien** [comment]
Noted. That's unfortunate and a bit strange. I'm sure it's something they don't plan on fixing. Oh, well, can't win them all.
