### ISSUE TITLE
Mentions do not work for names with specific characters in them

### ISSUE THREAD

**Issue by Calman102** [UWPCommunity/Quarrel#466]
So far I've witnessed a mention not working if the member you are mentioning has full stops and emojis in their Discord name. In fact I've only seen it working for members who have alphanumeric characters in them.

**Comment by Waddle-Doo** [comment]
This is very great information, but I'd like to reccomend this be merged with #443 and have that renamed to "Mentions do not function for names with non-alphanumeric characters".

**Comment by matthew4850** [comment]
> This is very great information, but I'd like to reccomend this be merged with #443 and have that renamed to "Mentions do not function for names with non-alphanumeric characters".

I agree this will be merged into #443
