### ISSUE TITLE
[Major Issue] Quarrel changes the activity status of the user to invisible without user input when starting the app.

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#468]
Tested and reproduced on Xbox One, Quarrel Insider 20.7.5.

I'm unsure of the exact conditions, but I have consistently reproduced this several times.

While this equates to a minor annoyance to end user, I believe any instance of the app changing account settings without user input is a security concern, and a cause for immediate investigation.

**Comment by matthew4850** [comment]
I would not consider this a security concern but I agree this is a problem
