### ISSUE TITLE
Background amélioration

### ISSUE THREAD

**Issue by aelisya** [UWPCommunity/Quarrel#47]
**Is your feature request related to a problem? Please describe.**
I don't really like the fact that a message send (when the page is closed), doesn't appear

**Describe the solution you'd like**
Is it possible to improve the function in the background so that you can leave the application constantly open (but in the area below the right of the spot bar (I forget its name)).

**Describe alternatives you've considered**
Receive a system notification (almost immedialy) when a message appears (as mytube does with the channels followed) it appears between 30 sec and 1 minute after publication

Thanks

**Comment by Avid29** [comment]
I’m rewriting the app entirely so soon none of this will be relevant, but…

#1 DMs should already be possible to open in the bottom right as myTube does. Channels not so much.

#2 MyTube does not have anything close to instant notifications. There’s limits that allow me only to check every 15 minutes. Same with myTube

Finally, remove ads are by account

**Comment by aelisya** [comment]
ok thanks for the response
