### ISSUE TITLE
misspell of word

### ISSUE THREAD

**Issue by aelisya** [UWPCommunity/Quarrel#48]
**Describe the bug**
A word is misspelled.

**To Reproduce**
1. Go to 'Account settings (in french version of the application)'
2. See under "Ajouter une image" (or add images in english)
3. "Suprimmer" is a spelling error.

**Expected behavior**
It would be written "Supprimer"

**Screenshots**
![Image of the misspell](https://cdn.discordapp.com/attachments/534038175471894528/594646540510035978/Annotation_2019-06-29_235212.png)

**Desktop (please complete the following information):**
 - Windows Version 1903

**Additional context**
I would like to make a pull request but I did not find which file needed to be edit in the sources.

**Comment by matthew4850** [comment]
It should be somewhere in here, select the correct language and use ctrl + f to help you find where it is.

**Comment by aelisya** [comment]
on my other thread he said he work on a new version, so i also signal the bug, like that it would be corrected also on the new app

**Comment by Avid29** [comment]
This is from the old version. 
Translation is not yet in new Quarrel and this issue is dated
