### ISSUE TITLE
Quarrel doesn't automatically mark read message

### ISSUE THREAD

**Issue by jaigak** [UWPCommunity/Quarrel#482]
Currently, when you read a message, it doesn't mark it as read so I need to manually mark it as read.

**Comment by Waddle-Doo** [comment]
Quarrel marks messages in a channel as read when you scroll down to the bottom bounds of the channel, just Discord does. This can be closed.

**Comment by jaigak** [comment]
It only marks if there are a lot of message that needs to be scrolled. If it’s a new channel with only a few messages it doesn’t mark it automatically.

**Comment by Calman102** [comment]
Can confirm, the only marker for whether a channel is read appears to be whether you have scrolled to the bottom, which cannot occur with channels with less than a full page of messages.

**Comment by Waddle-Doo** [comment]
For clarification, this issue could possibly be renamed to something along the lines of "channels with less than a full page of messages do not scroll to the bottom bounds of the page correctly".
