### ISSUE TITLE
Send friend request and send message isn't working from account info dialog

### ISSUE THREAD

**Issue by jaigak** [UWPCommunity/Quarrel#496]

**Comment by Waddle-Doo** [comment]
This is a duplicate of #376 , which was linked to and closed in #447 and merged into Insider 20.7.15. This can be closed.

**Comment by Waddle-Doo** [comment]
I request kindly that you provide longer, more concise descriptions of issues, always check the open and closed issues to make sure your report isn't a duplicate, and always be testing on the latest build of Quarrel Insider. I think the devs and other contributors would really appreciate it, it'd make life much easier.

Thanks! <3
