### ISSUE TITLE
Can't click on any link

### ISSUE THREAD

**Issue by jaigak** [UWPCommunity/Quarrel#497]

**Comment by Waddle-Doo** [comment]
Can you please elaborate on what this means?

**Comment by jaigak** [comment]
@Waddle-Doo Let's say you have an hyperlink in the chat. It appears in blue but clicking it doesn't do anything. I need to manually copy and paste it.

**Comment by Waddle-Doo** [comment]
Afaik Discord markdown doesn't allow for hyper-linking, so I'm not sure what you mean.

**Comment by jaigak** [comment]
@Waddle-Doo In Discord, if you enter a web link it will automatically become an hyperlink but you can't change the text. These links only work some time in Quarrel.

**Comment by Waddle-Doo** [comment]
Confirming that web links inside of embeds also do not work.
