### ISSUE TITLE
Loss of audio on XBOX One

### ISSUE THREAD

**Issue by sidneisouzajr** [UWPCommunity/Quarrel#501]
Every time I used Quarrel on XBOX One I lost audio during the game. It was necessary to return to Quarrel, hang up the call and perform again.

I think the problem is only during the game, but I don't know if it is a specific game - Call of Duty - or if it occurs in other games.

**Comment by Waddle-Doo** [comment]
This is a duplicate of #395 .

**Comment by matthew4850** [comment]
Closed as duplicate of #395
