### ISSUE TITLE
Register as a share target

### ISSUE THREAD

**Issue by jaigak** [UWPCommunity/Quarrel#505]
Share charm is a great feature and Quarrel should be support as a share target

**Comment by Waddle-Doo** [comment]
I'd like to hear Adam and Matthew's detailed thoughts on this, as they know much more about UWP insanity than I do, but a few notes of mine after doing some homework

1. The share charm you're referriing to was removed in Windows 10 over two years ago and has been replaced as of last documentation by a system wide context menu option

2. The logistics of actually implementing this, even if Quarrel could register, seem rather overwhelming in scope compared to the benefit of it

I think this is really low priority at best, but again, I'm not an expert.
API stuff isn't my thing, I just break the stuff and then report on it.

**Comment by matthew4850** [comment]
I would agree this is low priority but its certainly doable and has not been removed from Windows. We used to support it in old Quarrel and its certainly something we would like to add back at some point.

**Comment by jaigak** [comment]
The share charm that used to come at the right has been removed however the API still exist. Only the UI has been changed to a dialog box which is still used. It's extremely useful and every app should support it in my opinion.
