### ISSUE TITLE
Notifications dont work and the notifications settings button is greyed out

### ISSUE THREAD

**Issue by julianpoelmann** [UWPCommunity/Quarrel#508]
im probably missing the most obvious thing but if not is there a way to fix this
![afbeelding](https://user-images.githubusercontent.com/28513665/93233997-0a5b9180-f77c-11ea-89db-69397d150984.png)

**Comment by Waddle-Doo** [comment]
Notifications are unimplemented, still WIP. This can be closed, thanks. <3

**Comment by matthew4850** [comment]
I will leave this open just to make sure when notifications are implemented we don't forget to enable the button xD

**Comment by Waddle-Doo** [comment]
Okiedokie ❤
