### ISSUE TITLE
Fix System.OutOfMemoryException: Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.

Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.
 in Crash Group # 1466194250u

### ISSUE THREAD

**Issue by Avid29** [UWPCommunity/Quarrel#511]
### Reason ###

System.OutOfMemoryException: Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.

Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.

### Link to App Center ###

* [https://appcenter.ms/users/avid29-po8l/apps/Quarrel-Insider/crashes/errors/1466194250u](https://appcenter.ms/users/avid29-po8l/apps/Quarrel-Insider/crashes/errors/1466194250u)

**Comment by Waddle-Doo** [comment]
Avid, wtf? Is there something up with the german translation or is this just a new crash that happened to be reported in that localization?
