### ISSUE TITLE
Issue with App Performance on Xbox One

### ISSUE THREAD

**Issue by markstahman** [UWPCommunity/Quarrel#514]
Major crash resulting in loss of all previous messages in servers and direct messages,inability to make settings adjustments, receive or send text chat, and inability to use voice chat. Reinstalling, clearing cache, restarting and rebooting. Currently, the app is inoperable.

**Comment by matthew4850** [comment]
Unfortunately, due to starting university, I won't be able to look into this soon, if you have any technical experience you can clone the source code and take a look yourself.

**Comment by markstahman** [comment]
Thank you for reaching out. I have less than no experience working with computer code, and do not desire to break something more than it is already broken. Thank you again.
