### ISSUE TITLE
interactions with API causes accounts to be automatically flagged for abuse and eventually suspended. requesting that app be immediately pulled from the microsoft store to avoid further jeopardizing user accounts.

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#517]
.

**Comment by Waddle-Doo** [comment]
i have sent an attachment to Adam's email regarding this as github is giving me trouble.

**Comment by matthew4850** [comment]
Do you have any examples of this happening?

**Comment by Bluscream** [comment]
It happened to my old dc account too

**Comment by Bluscream** [comment]
But only with quarrel (ripcord works fine)

**Comment by matthew4850** [comment]
@Bluscream How long ago was this and how do you know Quarrel caused this?

**Comment by Bluscream** [comment]
A few months and i only used quarrel and the official vanilla client at that time

**Comment by matthew4850** [comment]
> A few months and i only used quarrel and the official vanilla client at that time

What did Discord say was the reason for suspending your account?

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/98456115-aea8f580-2179-11eb-9819-bdddfaaa9e47.png)

**Comment by Bluscream** [comment]
@matthew4850 selfbotting

_Sent from my Lenovo TB-X606F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
