### ISSUE TITLE
Constantly forces my account online

### ISSUE THREAD

**Issue by Junkaat** [UWPCommunity/Quarrel#525]
I'm no longer logged into quarrel with my main account but it forces me to stay on preventing discord mobile to give me notifications

**Comment by Avid29** [comment]
There's a keep alive background task for background notifications. You can disable this in settings

**Comment by Junkaat** [comment]
Where is that?

**Comment by Junkaat** [comment]
I don't actually see anything like that on the app, the notifications tab is greyed out

**Comment by Junkaat** [comment]
Also I have it on my Xbox so I can't do that

**Comment by Junkaat** [comment]
I quit trying. I've tried everything.
