### ISSUE TITLE
Calls on Xbox One X suddenly drop, with no indication that the call has ended

### ISSUE THREAD

**Issue by stamminator** [UWPCommunity/Quarrel#528]
I have tried Quarrel for the first time the other day and was able to get a call with two other people working. Unfortunately, several minutes into my calls, the call would suddenly end, but there was no indication. I had to figure it out after a couple of awkward minutes of talking to myself. So I think there are two distinct issues here:
1. Prevent sudden crashing of calls
2. If a crash takes place, an audio alert needs to let the user know that it has ended so they can go reestablish the call without wasting time.

**Comment by Gurrman375** [comment]
The reason calls crash so often on Xbox is that a background task has not been set up in order to prevent crashes.
