### ISSUE TITLE
Complete Breakdown

### ISSUE THREAD

**Issue by markstahman** [UWPCommunity/Quarrel#533]
I was using this app on an Xbox One while it was barely functioning. No way to send or recieve texts, no way to joinnew servers, no way to accept friend requests, no way to to danything but join the one VC on the one server I was able to join. And now I cant even access that server. What happened? is there any way to fix it?

**Comment by Crimson-Blade** [comment]
Is this even being developed? Plus it's against discord's TOS lol, but either way.

**Comment by Crimson-Blade** [comment]
I tried it out today, but it barely works. One thing i do like though is the fluent UI. Looks very windows like

**Comment by KibSquib48** [comment]
> Is this even being developed? Plus it's against discord's TOS lol, but either way.

no update since october 2020, rip

**Comment by GabeTC** [comment]
Doesn't boot for me on either Windows or Xbox
