### ISSUE TITLE
Quarrel [Rewrite] crashes when I click on a section of a server I don't have access to

### ISSUE THREAD

**Issue by MarcAnt01** [UWPCommunity/Quarrel#54]
**Describe the bug**
The title is enough
**To Reproduce**
1. Go to a server
2. Click on a section you don't have access to.

**Expected behavior**
I'm not very expert about Discord stuff, but official client doesn't neither show those sections
**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Home 1903

**Smartphone (please complete the following information):**
 - Device: [e.g. Lumia 950]
 - Windows Mobile Version [e.g. 1607]

**Additional context**

**Comment by matthew4850** [comment]
Closed by ba3c8da7ee93e8e78f9a2297c5e0dd9c7b8532bf
