### ISSUE TITLE
the app is missing on microsoft store

### ISSUE THREAD

**Issue by ddodogames** [UWPCommunity/Quarrel#544]
When Trying To Go To [Official Quarrel Microsoft Store Link](https://www.microsoft.com/en-gb/p/quarrel-unofficial-discord-client/9nbrwj777c8r?activetab=pivot:overviewtab) it shows this 
![image](https://user-images.githubusercontent.com/69091682/137565177-6cf66aa2-dfac-48f1-a2af-ed0c14e166be.png)

**Comment by ddodogames** [comment]
the question is what happened to Quarrel ms store link?

**Comment by ddodogames** [comment]
To Be Honest I Dont Know if its Only Happening To Me Or For Everyone

**Comment by jobukkit** [comment]
Same here.

**Comment by ddodogames** [comment]
To Be Honest Looks Like This Project is Now Completely Dead

**Comment by ddodogames** [comment]
alright im back with a Official response from the dev
![image](https://user-images.githubusercontent.com/69091682/138494145-b098063c-2ef5-4b16-abd4-730183785f1a.png)

**Comment by ghost** [comment]
It's been **months**, still not in store.
Is the project dead?

**Comment by ddodogames** [comment]
idk
