### ISSUE TITLE
Store link in the github not working; Please change it

### ISSUE THREAD

**Issue by Joel-Nickson** [UWPCommunity/Quarrel#545]

**Comment by Joel-Nickson** [comment]
Sorry I did not see the duplice issue that was already created #544

**Comment by ddodogames** [comment]
lts fine

**Comment by ddodogames** [comment]
you can keep this issue opened if you want

**Comment by ddodogames** [comment]
![image](https://user-images.githubusercontent.com/69091682/138494098-3fb78361-0dfb-4f73-93a7-92fddcba2c7b.png)
