### ISSUE TITLE
WinUI 2.7

### ISSUE THREAD

**Issue by needlesslygrim** [UWPCommunity/Quarrel#546]
Is Quarrel going to be upgraded to WinUI 2.7 to take advantage of the new Windows 11 look?

**Comment by BreeceW** [comment]
It’s very important that acrylic be replaced with mica.

**Comment by rafal06** [comment]
> It’s very important that acrylic be replaced with mica.

I think fixing bugs that make this app unusable is way more important ಠ_ಠ

**Comment by matthew4850** [comment]
> It’s very important that acrylic be replaced with mica.

no

**Comment by RokeJulianLockhart** [comment]
@Avid29, has this been implemented?

**Comment by Avid29** [comment]
The app is going through a full rewrite, so all existing issues have been closed
