### ISSUE TITLE
[Rewrite] Sometimes propics overlap in direct messages

### ISSUE THREAD

**Issue by MarcAnt01** [UWPCommunity/Quarrel#55]
**Describe the bug**

The title is enough

**To Reproduce**
1. Go to direct messages;
2. Open a chat

**Expected behavior**
Behave normally

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/60584190-e08f9800-9d8c-11e9-9001-8afa44a12d35.png)

**Desktop (please complete the following information):**
 - Windows 10 Home 1903

**Smartphone (please complete the following information):**
 - Device: [e.g. Lumia 950]
 - Windows Mobile Version [e.g. 1607]

**Additional context**

**Comment by matthew4850** [comment]
This is a consequence of some embeds not being implemented.
