### ISSUE TITLE
myPeople integration

### ISSUE THREAD

**Issue by matthew4850** [UWPCommunity/Quarrel#60]

**Comment by MarcAnt01** [comment]
MyPeople has been removed now

**Comment by matthew4850** [comment]
Where did Microsoft say this, my people still exists for me

**Comment by MarcAnt01** [comment]
> Where did Microsoft say this, my people still exists for me

I don't have MyPeople any longer since I have taken my new laptop (might have been removed with 1909), but Microsoft has announced that this feature wouldn't be improved any longer in the past

**Comment by MarcAnt01** [comment]
@matthew4850 I checked better and there was no official announcement. It just used to show a deprecation info in 19H1 insider builds and later has been removed

**Comment by matthew4850** [comment]
Yes my people is no longer being worked on by Microsoft but it has not been removed.

**Comment by MarcAnt01** [comment]
> Yes my people is no longer being worked on by Microsoft but it has not been removed.

I can't find it in my laptop and I checked another PC in my house and it's not present, neither

**Comment by matthew4850** [comment]
Perhaps you have it disabled, it works on all my devices.

**Comment by MarcAnt01** [comment]
> Perhaps you have it disabled, it works on all my devices.

Nope, never touched it
