### ISSUE TITLE
Quarrel only accepts tokens from accounts with 2FA enabled

### ISSUE THREAD

**Issue by Not-a-web-Developer** [UWPCommunity/Quarrel#606]
When trying to use a token to log into Quarrel, the token is only considered valid if 2FA is enabled on the account.

how this works is basically this:
discord tokens usually look like `token`; however, if you have 2FA enabled, the token instead looks like `mfa.token` which is what's considered valid by Quarrel, and the login button becomes clickable.

I don't know if this was intentional or not, if it's intentional then the issue can be closed.

**Comment by Avid29** [comment]
Good catch. This is not intentional, and I'll go adjust the Regex before the next release.

Thank you very much for your input

**Comment by Avid29** [comment]
Fixed. A careless error was made in the adjusted regex to add explicit case insensitivity
