### ISSUE TITLE
Native game chat (talk) not available when using Quarrel

### ISSUE THREAD

**Issue by ashchristopher** [UWPCommunity/Quarrel#614]
When using Quarrel, in-game talk is not available on xbox (XBOX Series X). In-game audio from other players is not heard, and you can not interact with players in game using voice chat. The experience is similar to that of using an XBOX party-chat.

Expected:
If using quarrel, a player should be able to hear the in-game voice chat as well as the discord chat. Additionally, a player should be able to interact with both in-game voice chat and Discord chat.

**Comment by Avid29** [comment]
There's a full rewrite on the way, and this is clearly a bug report from old Quarrel. So I'm going to mark this old and close it as any bugs from the currently published version have no relevance to current development.
