### ISSUE TITLE
Mute/deafen toggles non-functional (Bug)

### ISSUE THREAD

**Issue by GH0STP4WZ** [UWPCommunity/Quarrel#615]
Hi, So I've been using quarrel for a little bit as alternative when when my Powercord client doesnt want to run (This happens a lot.)
I really enjoy participating in VC's, and often end up deafening when housemates require something of me. On Quarrel, the mute and deafen toggles do not function correctly. When toggled, the other users in VC report that they can still hear me when muted. They also still see the icon fo me being muted as well as deafened. Whilst defeaned, audio from other users still comes through. Also it doesn not mute you when deafened.

**Comment by Avid29** [comment]
There's a full rewrite on the way, and this is clearly a bug report from old Quarrel. So I'm going to mark this old and close it as any bugs from the currently published version have no relevance to current development.
