### ISSUE TITLE
Server crushing Quarrel on Xbox Series

### ISSUE THREAD

**Issue by SlidingPogba** [UWPCommunity/Quarrel#616]
On a xbox series I have a server that's crashing quarell, I tried to rejoin it, rename it (I thought problem was in a & symbol). Even reinstalled quarell - nothing helped.

I can provide invite link if it necessary

**Comment by SlidingPogba** [comment]
![Screenshot_2022-06-08-14-09-27-387_com miui gallery](https://user-images.githubusercontent.com/91668287/172602333-e2c99011-e819-49cc-9f5d-c6764dcedfa8.jpg)

Second before disaster 😅

**Comment by Avid29** [comment]
There's a full rewrite on the way, and this is clearly a bug report from old Quarrel. So I'm going to mark this old and close it as any bugs from the currently published version have no relevance to current development.
